/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gift-two.gltf --transform 
Files: gift-two.gltf [33.39KB] > C:\Users\Admin\Downloads\a_gift_box\gift-two-transformed.glb [88.98KB] (-166%)
Author: Rofnay (https://sketchfab.com/Rofnay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-gift-box-1a53662e300b4d7e9ae39eba101409ea
Title: A Gift Box
*/
import { useAnimations, useGLTF } from "@react-three/drei";
import { Group } from "three";
import { RefObject, useEffect, useRef, useState } from "react";
import useSound from "use-sound";
import { useFrame } from "@react-three/fiber";
import ExplosionEffect from "../effect/ExplosionEffect";
import { IProps } from "../../types/gift.props";
import { calculateFallSpeed, useGift } from "./common";
const modelGiftTwo = import.meta.env.BASE_URL + "assets/model/gift-two.glb";

export function GiftTwo({ position, product, onClick }: IProps) {
  const {
    ref,
    onUserClickOnGift,
    giftVisible,
    nodes,
    materials,
    exploding,
    giftPosition,
  } = useGift({ position, product, onClick }, modelGiftTwo);

  return (
    <>
      <group
        ref={ref}
        position={position}
        dispose={null}
        onClick={onUserClickOnGift}
        visible={giftVisible}
        scale={1.6}
      >
        <mesh
          geometry={nodes.Giftbox_GiftMat_0.geometry}
          material={materials.GiftMat}
          position={[0, -1, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      {exploding && <ExplosionEffect position={giftPosition} />}
    </>
  );
}

useGLTF.preload(modelGiftTwo);
